### ISSUE TITLE
Bytes greater than 127

### ISSUE THREAD

**Issue by hamidnaghi** [MacroYau/Blue2Serial#9]
Once I send the bytes with value of 128 to 255 by Bluetooth to Android then I see different bytes. I receive -17,  -65, -67 instead of 128 to 255. But, it works with 0 to 127. Something happens to "(byte[]) msg.obj" with negative values in the 
  private final Handler mHandler = new Handler()  
in the section
 case MESSAGE_READ:
                    byte[] bufferRead = (byte[]) msg.obj;

Would you please resolve it?
Best regards
Hamid Naghizadeh

**Comment by MacroYau** [comment]
This is due to the fact that [primitives in Java, including `byte`, are signed](http://stackoverflow.com/a/4266841). You can implement `int unsignedByte = signedByte & 0xFF` as instructed in the Stack Overflow answer as a workaround.

**Comment by hamidnaghi** [comment]
Thank you Macro,
But, If I send any negative value then it only receive -17, -65, -67.

**Comment by hamidnaghi** [comment]
Even, If I implement int unsignedByte like your comment then I will receive 3 bytes 239, 191, 189 instead of 1 byte for each negative value I send out. And it is same as negative one, just in unsigned value.

**Comment by MacroYau** [comment]
Can you specify your expected input and output?

**Comment by hamidnaghi** [comment]
I'm sending 0 to 255 from another bluetooth to android and I'm expecting to receive same number on Android, but I'm receiving 0 to 127 for numbers 0 to 127 I send which is match and OK, but for other numbers between 127 to 255 I'm receiving only 63, not same number that I sent.

**Comment by hamidnaghi** [comment]
The input from other bluetooth is an array with 256 elements contains 0 to
255 that I'm sending to Android, But, the output on Android is 0 to 127 and
only 63 for the data input between 128 to 255.

**Comment by MacroYau** [comment]
@hamidnaghi Now I understand your issue after testing with an Arduino Bluetooth module. It is caused by the handling of the received bytes in the [`SPPService` class](https://github.com/MacroYau/Blue2Serial/blob/4630436ef52587139d9473c4c22fd3f27313e91a/library/src/main/java/com/macroyau/blue2serial/SPPService.java#L208), which incoming bytes are buffered into a String (and hence distorted the bytes since some of them cannot be properly encoded).

A simple workaround would be encoding the values as Strings on the device sending the data, if possible. Alternatively, you can consider modifying the `SPPService` class to enable it to appropriately handle the incoming bytes.
